### ISSUE TITLE
Why this code isn't working?

### ISSUE THREAD

**Issue by markolofsen** [norkunas/youtube-dl-php#58]
Why this code isn't working?
Variable $video are empty. All dependencies libraries was updated successfully.
I didn't any changes in my code and it worked few month ago.

```
                $identity = 'Tiye0BqxJS4';
                $yt = new YoutubeDl([
                    'skip-download' => true,
                    'format' => 'best[ext=mp4]',
                ]);

                $video = $yt->download('https://www.youtube.com/watch?v='.$identity);
                print_r($video);
                exit();
```

**Comment by norkunas** [comment]
It works for me. You must set download path

**Comment by markolofsen** [comment]
@norkunas Thanks, you was right

**Comment by muhammadnomangul** [comment]
i have installed you repository .. but i got this when call for video download ..


"youtube-dl" executable was not found. Did you forgot to add it to environment variables? Or set it via $yt->setBinPath('/usr/bin/youtube-dl').

what should be do ?

**Comment by norkunas** [comment]
Error message explains what you should do, no? :) Set the binary path to your youtube-dl installation

**Comment by muhammadnomangul** [comment]
how to add that binary path

**Comment by norkunas** [comment]
Call `$yourObject->setBinaryPath('/path/to/your/youtube-dl');`

**Comment by muhammadnomangul** [comment]
i have used composer cmd to installed repository . 
then that store in vendor

**Comment by norkunas** [comment]
This library depends on https://rg3.github.io/youtube-dl/ so you need to download it.
Did you read the README file? https://github.com/norkunas/youtube-dl-php/blob/master/README.md

**Comment by muhammadnomangul** [comment]
yes i  have installed youtube-dl  using this 
sudo wget https://yt-dl.org/downloads/latest/youtube-dl -O /usr/local/bin/youtube-dl

sudo chmod a+rx /usr/local/bin/youtube-dl

**Comment by norkunas** [comment]
So set in your code binary path to /usr/local/bin/youtube-dl

**Comment by muhammadnomangul** [comment]
yes thanks
its working now

**Comment by norkunas** [comment]
Good.

**Comment by guig3** [comment]
help me???
 {"error":true,"message":"\"youtube-dl\" executable was not found. Did you forgot to add it to environment variables? Or set it via $yt->setBinPath('\/usr\/bin\/youtube-dl')."}

**Comment by norkunas** [comment]
@guig3 the library can't find your `youtube-dl` executable. Did you download it? If yes you can try to set it as the error says with `$yt->setBinPath();` so it will know where to look for it.

**Comment by guig3** [comment]
@norkunas Good morning brother, so I installed ffmpeg and when I type the command to install Yotube-dl, it appears that the command is invalid, could you help me?
I used puTTY to install ffmpeg

**Comment by norkunas** [comment]
@guig3 what command did you run to install youtube-dl?

**Comment by guig3** [comment]
@norkunas I was trying these commands
```
sudo wget https://yt-dl.org/downloads/2016.05.10/youtube-dl -O /usr/local/bin/youtube-dl
sudo chmod a+rx /usr/local/bin/youtube-dl
```
Source => https://github.com/MichaelBelgium/Youtube-to-mp3-API

**Comment by guig3** [comment]
> @norkunas I was trying these commands
> 
> ```
> sudo wget https://yt-dl.org/downloads/2016.05.10/youtube-dl -O /usr/local/bin/youtube-dl
> sudo chmod a+rx /usr/local/bin/youtube-dl
> ```
> Source => https://github.com/MichaelBelgium/Youtube-to-mp3-API

I used this command too `composer create-project michaelbelgium/youtube-to-mp3 [directoryname]`
link test => http://botecosertanejo.com/ytconverter/convert.php?youtubelink=https://www.youtube.com/watch?v=5aWgoO0capE

**Comment by norkunas** [comment]
Amd what errors did you get?

2019-02-07, kt 18:03 guig3 <notifications@github.com rašė:

**Comment by norkunas** [comment]
Also 2016.05.10 is a very old version,i suggest to use latest

2019-02-07, kt 18:07 Tomas Norkūnas <norkunas.tom@gmail.com rašė:

**Comment by guig3** [comment]
@norkunas Do you know where I can get the updated version? I do not have much knowledge on this yet, if you can help me I'll be very grateful

**Comment by norkunas** [comment]
Before one more question :) are you using windows or unix?

2019-02-07, kt 18:36 guig3 <notifications@github.com rašė:

**Comment by guig3** [comment]
linux cPanel hosting

**Comment by norkunas** [comment]
Does your hosting allows you to install your own binaries?

**Comment by guig3** [comment]
Hey bro, yes it's allowed

**Comment by norkunas** [comment]
@guig3 you should follow instructions for download youtube-dl in https://rg3.github.io/youtube-dl/download.html so you'll get the latest version.

Secondly you should call `$yt->setBinPath('/usr/local/bin/youtube-dl');` so the library will directly call this and it should work.

**Comment by winbotscript** [comment]
@norkunas how to set call $yt->setBinPath('/usr/local/bin/youtube-dl ???

Tell me step by step cause i am beginner learning API

**Comment by norkunas** [comment]
@winbotscript binary path should point directly to the `youtube-dl` or `youtube-dl.exe`,
if you are on unix then the you can locate it with `whereis youtube-dl`, on windows the path should be where you placed it after download.

**Comment by winbotscript** [comment]
@norkunas so what must i do? i am use vps centos 6, tell me please to resolve this issue

**Comment by norkunas** [comment]
@winbotscript please explain what problem are you experiencing.

**Comment by winbotscript** [comment]
I got issue {"error":true,"message":"\"youtube-dl\" executable was not found. Did you forgot to add it to environment variables? Or set it via $yt->setBinPath('\/usr\/bin\/youtube-dl')."}

Which youtube-dl
/usr/local/bin/youtube-dl

How to resolve that ???

**Comment by winbotscript** [comment]
@norkunas I got issue {"error":true,"message":""youtube-dl" executable was not found. Did you forgot to add it to environment variables? Or set it via $yt->setBinPath('/usr/bin/youtube-dl')."}

Which youtube-dl
/usr/local/bin/youtube-dl

How to resolve that ???

**Comment by norkunas** [comment]
@winbotscript so after downloading the https://ytdl-org.github.io/youtube-dl/ where did you store it on your device?

**Comment by winbotscript** [comment]
@norkunas i am install sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl

sudo chmod a+rx /usr/local/bin/youtube-dl

**Comment by norkunas** [comment]
So this should work:
```
require __DIR__ . '/vendor/autoload.php';

use YoutubeDl\YoutubeDl;

$dl = new YoutubeDl([
  // .. your configuration
]);
$yt->setBinPath('/usr/local/bin/youtube-dl');
```

**Comment by winbotscript** [comment]
@norkunas where's that file ?

**Comment by norkunas** [comment]
@winbotscript which file? If you are asking about the php code, then store in your configured webserver path

**Comment by winbotscript** [comment]
I am use Youtube-to-mp3-API in path /home/admin/domain/api/ytmp3

**Comment by norkunas** [comment]
You mean this https://github.com/MichaelBelgium/Youtube-to-mp3-API/ ?
You should open `convert.php` file and then after `$dl = new YoutubeDl($options);`
add the `$yt->setBinPath('/usr/local/bin/youtube-dl');` method call.

**Comment by winbotscript** [comment]
@norkunas thanks for your help, but i get an issue again {"error":true,"message":"The Process class relies on proc_open, which is not available on your PHP installation."}

My PHP 7.1.30 (cli)

Help me please

**Comment by norkunas** [comment]
As the error says you need to host your converter where your php supports the `proc_open` function. If you are using hosting, then contact with support. If you manage your own server enable the function. This is the point where I cannot help you anymore.

**Comment by xiisaiki** [comment]
i have the same problem 
    "message": "\"youtube-dl\" executable was not found. Did you forgot to add it to environment variables? Or set it via $yt->setBinPath('/usr/bin/youtube-dl')."

i add this to environnement variables , im not sure if it's right but i add the variable and it's path to executable file

but still have the same problem 

please help me !!

**Comment by hirazzz** [comment]
Respected sir Norkunas. I am implementing this repo : https://github.com/MichaelBelgium/Youtube-to-mp3-API
I also implemented $dl->setBinPath('/usr/local/bin/youtube-dl'); after insatalling youtbe-dl application file.
But i am getting following error. 
message: "Unable to launch a new process."
Can you please help. Would be thankful.

**Comment by norkunas** [comment]
@hirazzz please create new issue

**Comment by rahulparakhiya2** [comment]
Uncaught YoutubeDl\Exception\ExecutableNotFoundException: "youtube-dl" executable was not found. Did you forgot to configure it's binary path? ex.: $yt->setBinPath('/usr/bin/youtube-dl') ?.

**Comment by norkunas** [comment]
@rahulparakhiya2 and?
